Description:
  Written by DaEun Kim.
  This template deploys a security group for instances in VPC.


Parameters:
  EnvironmentName:
    Description: An environment name which will be prefixed to resource names
    Type: String


Resources:
  LaunchConfigforWebApp:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          # !/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://udacity-demo-1/udacity.zip .
          unzip -o udacity.zip

      ImageId: ami-005bdb005fb00e791
      SecurityGroups:
        Fn::ImportValue:
         !Sub "${EnvironmentName}-SECURITY-GROUP"

      InstanceType: t3.small
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          EBS:
            VolumeSize: "10"

