Description:
  Written by DaEun Kim.

  This template deploys
    * a VPC with 2 public subnets and 2 private subnets spread across 2 Availability Zones.
    * an Internet Gateway routing on the public subnets by default.
    * a pair of NAT Gateways (one on each AZ).
    * a router for private subnets.

# Don't hard-code resource value in CloudFormation script or you could break already tested script.
# Make parameters and give them to this script.
Parameters:
  EnvironmentName:
    Description: An environment name which will be prefixed to resource names
    Type: String

  VpcCIDR:
    Description: IP range (CIDR notation) for VPC
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayForPublicSubnets:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGatewayForPublicSubnets
      VpcId: !Ref VPC
